version: '3'
services:
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s

    pgsql:
        image: 'postgres:15'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-pg}'
            POSTGRES_DB: '${DB_DATABASE:-pg}'
            POSTGRES_USER: '${DB_USERNAME:-pg}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-pg}'
        volumes:
            - './local-data/postgres-data:/var/lib/postgresql/data:rw'
            - './docker-envs/sail/database/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - pg_isready
                - '-q'
                - '-d'
                - '${DB_DATABASE:-pg}'
                - '-U'
                - '${DB_USERNAME:-pg}'
            retries: 3
            timeout: 5s

networks:
    sail:
        driver: bridge

volumes:
    sail-redis:
        driver: local
    sail-pgsql:
        driver: local
